### ISSUE TITLE
Potential usability issue

### ISSUE THREAD

**Issue by Valera** [quickdocs/quickdocs-web#1]
In project search results, Project names are displayed with bold and dark blue font face, link to project repo is displayed as traditional web link (bold & blue).

![Screenshot](https://user-images.githubusercontent.com/131263/132131028-779563bc-48eb-4e92-b19f-ddb2cbb453b3.png)

With this font settings repo links are "stealing" clickability from project pages. Personally, I do not recognized them as clickable for several first visits to qickdocs.org. I think many people experience it too. 

There are many solutions, the most straightforward one being coloring project page link to blue.

**Comment by fukamachi** [comment]
Sounds reasonable.
It probably won't confuse you if no repository link is displayed, right?
I'll try to fix it in some way.

**Comment by fukamachi** [comment]
Fixed at 9f74061d943551ce6893998040c9e7176baa8004.
