### ISSUE TITLE
Can't command-click on depenency/dependent links to open in a new tab

### ISSUE THREAD

**Issue by cellularmitosis** [quickdocs/quickdocs-web#2]
For example, open up this page: https://quickdocs.org/babel

All of the dependencies and dependents are links, but they don't behave like regular links.  You can't right-click on them to get the typical "link" context menu (with options like "Open link in new tab"), and you can't command+click on them to open in a new tab.

**Comment by fukamachi** [comment]
Thanks for pointing it out.
It will be fixed as I think it's not a difficult problem to fix.

**Comment by cellularmitosis** [comment]
Thanks so much!
